### ISSUE TITLE
Getting an error when trying to auth a youtube account. 

### ISSUE THREAD

**Issue by imkevinabraham** [SocialiteProviders/YouTube#5]
I followed the instructions on [http://socialiteproviders.github.io/providers/youtube/](http://socialiteproviders.github.io/providers/youtube/). But when trying to auth a user I get an error that reads: 
```
FatalErrorException in Provider.php line 77:
Call to undefined method SocialiteProviders\YouTube\Provider::getAccessToken()
```

I've tried:
- `composer update`
- `composer dump-autoload`
- `php artisan clear-compiled` 
- and `php artisan cache:clear`

Still getting the same error. Is there a way to fix this issue?
<img width="1129" alt="screen shot 2016-06-22 at 11 44 42 pm" src="https://cloud.githubusercontent.com/assets/10243223/16268893/7fd3ebc2-38d3-11e6-8064-7a42adda35e6.png">

**Comment by DraperStudio** [comment]
You seem to be using an old version. Was fixed with https://github.com/SocialiteProviders/YouTube/releases/tag/v2.0.2.

**Comment by imkevinabraham** [comment]
Thanks, I tried to update but got an error saying I need the socialiteproviders/manager. So I tried to install the manager but ran an into a conflict with the trying to use v2 of the manager which is required by youtube and 37 signals which requires v1. The error is: 

```
composer require socialiteproviders/manager
Using version ^2.1 for socialiteproviders/manager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - socialiteproviders/37signals v1.1.2 requires socialiteproviders/manager ~1.0 -> satisfiable by socialiteproviders/manager[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4] but these conflict with your requirements or minimum-stability.
    - socialiteproviders/37signals v1.1.2 requires socialiteproviders/manager ~1.0 -> satisfiable by socialiteproviders/manager[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4] but these conflict with your requirements or minimum-stability.
    - socialiteproviders/37signals v1.1.2 requires socialiteproviders/manager ~1.0 -> satisfiable by socialiteproviders/manager[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4] but these conflict with your requirements or minimum-stability.
    - Installation request for socialiteproviders/37signals (locked at v1.1.2, required as ^1.1) -> satisfiable by socialiteproviders/37signals[v1.1.2].


Installation failed, reverting ./composer.json to its original content.
```
Is there a way to fix this and have both?

PS: I think your package is an awesome concept.

**Comment by DraperStudio** [comment]
Seems like you have a v1 Provider installed and try to install a v2 Provider. This conflicts because you can't have the v1 and v2 of the Manager installed.

**Comment by imkevinabraham** [comment]
Thanks that fixed the issues, Your doing great work!
