### ISSUE TITLE
Refresh token is always null.

### ISSUE THREAD

**Issue by imkevinabraham** [SocialiteProviders/YouTube#6]
Refresh token for youtube is always null. I've followed the instructions to implement the package and am able to successfully authenticate a user but the response always returns `+refreshToken: null`. How would I go about getting the refresh token when using this package?

**Comment by DraperStudio** [comment]
If YouTube doesn't send back the refresh token it won't be set.

This is where the refresh token gets set https://github.com/laravel/socialite/blob/2.0/src/Two/AbstractProvider.php#L197-L212
